# Generated by Django 4.1.3 on 2022-12-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nominal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("biaya", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="donasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=50)),
                ("kode", models.IntegerField(null=True)),
                ("email", models.CharField(max_length=40)),
                ("waktu", models.DateTimeField(auto_now_add=True)),
                ("deskripsi", models.TextField()),
                (
                    "nominal_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tlaut_apps.nominal",
                    ),
                ),
            ],
        ),
    ]
