# Generated by Django 4.1.3 on 2022-12-23 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tlaut_apps", "0002_metode_donasi_metode_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kegiatan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jenis_aksi", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="donasi",
            name="kode",
        ),
        migrations.AlterField(
            model_name="donasi",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="metode",
            name="bank",
            field=models.CharField(max_length=35),
        ),
        migrations.CreateModel(
            name="LaporAksi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_komunitas", models.CharField(max_length=50)),
                ("lokasi_aksi", models.CharField(max_length=50)),
                ("waktu_aksi", models.CharField(max_length=50)),
                ("deskripsi_aksi", models.TextField()),
                ("perkem_aksi", models.CharField(max_length=50)),
                ("perkem_dana", models.CharField(max_length=50)),
                ("perkem_deskripsi", models.TextField()),
                ("perkem_aksi2", models.CharField(max_length=50)),
                ("perkem_dana2", models.CharField(max_length=50)),
                ("perkem_deskripsi2", models.TextField()),
                ("perk_dana_total", models.CharField(max_length=50)),
                (
                    "kegiatan_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tlaut_apps.kegiatan",
                    ),
                ),
            ],
        ),
    ]
